---
dontChroot: false
timeout: 900
script:
    - "-rm ${ROOT}/etc/calamares/scripts/try-v3"
    - command: "pacman-key --init"
    - command: "pacman-key --populate archlinux cachyos"
    - command: "sed -i 's/SigLevel.*/SigLevel = Never/g' /etc/pacman.conf"
    - command: "pacman -Sy"
