# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# reanable running 90-mkinitcpio-install.hook for installed system
---

dontChroot: false
timeout: 3600
script:
    - command: "sh -c 'command -v sdboot-manage >/dev/null && sdboot-manage gen || echo \"sdboot-manage not installed, skipping (using GRUB)\"'"
